### ISSUE TITLE
TM7 to json

### ISSUE THREAD

**Issue by Johnferguson1440** [OWASP/threat-dragon#1060]
**Describe what problem your feature request solves**:

I have an old file from version 1.6 which is a tm7 file. I would like a way to convert the file to your expected json format. 
When i drag and drop it says only files ending in .json are supported.
**Describe the solution you'd like**:

Either the import should support the tm7 file and do the conversion for you when you import it. Or need a utility to be able to update the file type.
**Additional context**:

I would prefer not to have to recreate the whole thing.....

**Comment by jgadsden** [comment]
Hello @Johnferguson1440

There is a [separate utility in the version 1.6.x branch](https://github.com/OWASP/threat-dragon/tree/archive-legacy-v1.x/utils/TMT2TD) that converts from TM7 to threat dragon version 1.6.x format

Version 1.6.x always used its own threat dragon format json files when reading and writing, rather than TM7 file format, so your old version 1.6.x file is probably in threat dragon version 1.6.x format already.

Once your files are in threat dragon version 1.6.x format then threat dragon version 2.x will read them and can then write the files in threat dragon version 2.x format

**Comment by Johnferguson1440** [comment]
Thank You jgadsden I will try that out and see. I saw that this was mentioned in some docs but the links did not point to where yours does.

**Comment by Johnferguson1440** [comment]
That worked for me any reason why this isnt part of the import for version 2 and on?

**Comment by jgadsden** [comment]
really good point you make @Johnferguson1440 , just that it is a python script and Threat Dragon is written in Javascript
It is certainly possible to do, but we have nobody with the time to implement it
