### ISSUE TITLE
Increase number of browsers tested

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#142]
It would be good to increase the number of browsers we test against, at present it is:
- Chrome
- Firefox
- IE
- PhantomJS

Consider using Karma-detect-browsers: https://www.npmjs.com/package/karma-detect-browsers
to increase coverage to:
- Opera
- Safari
- Edge

**Comment by lreading** [comment]
Because we will have #90 as part of the build, I would suggest cross-browser testing during the e2e part.  I believe browserstack has a free option for open source projects.  I'll see if I can get us enrolled in that program and do cross browser testing as part of the build process.

**Comment by lreading** [comment]
After investigating a bit more, I believe that [cypress](https://www.cypress.io/) is the way forward.  I'll be merging into the v2-development branch soon with the e2e tests rewritten as cypress tests.  The cypress framework is significantly less verbose, and offers some other benefits, including local e2e testing using electron.  This will be important for the desktop component of Threat Dragon moving forward, as we can be more confident that things are working as expected prior to bundling a release.

BrowserStack does, indeed, offer free services to open source projects.  We get 5 parallel threads.  This is generous and enough for our use case.

Unfortunately, a limitation of Cypress is the browser support.  It currently only supports Chrome, Firefox, Edge and Electron.  The Browserstack runner supports Chrome, Firefox and Edge.  For that reason, and the limitation of 5 parallel tests, I've configured the tests to run on windows for Chrome, Firefox and Edge, and Mac OS (Big Sur) Chrome and Firefox.  While we could also technically test edge on Mac OS, we'd have to run that separately, as we would be out of headroom for the license that Browserstack has given us.  I honestly don't believe too many users on MacOS have opted into Edge at this point anyways.

The cross-browser testing is time consuming and will only get longer as more tests are added.  Because of that, the main CI pipeline will be updated to run the CI tests on Chrome and Firefox only (as they currently were), and the cross-browser testing will happen on merges to master.

**Comment by lreading** [comment]
v2 is maturing and the e2e / browser testing has been running without issue for at least a couple months now.  More tests need to be added, but the browser coverage for e2e tests can be found here: https://www.threatdragon.com/docs/development/testing/e2e.html
