### ISSUE TITLE
Auto shape trust boundries

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/threat-dragon#190]
Hi,

it's very hard to shape a trust boundary like a rectangle to have a very neat and clean threat model, any chance we can have an extra feature in drawing :)? 

Bests, Ali.

**Comment by jgadsden** [comment]
Hello @Ali-Razmjoo - this is something that does come up from various requests. I think @lreading is implementing this in version 2.0 (due out end of this year or so) . It was proving too difficult to implement with our existing, and out of date, jointjs drawing package so that is why it is deferred to version 2.0

@lreading do you mind if I assign this to you? I think you are working on it

**Comment by lreading** [comment]
https://github.com/OWASP/threat-dragon/issues/54#issuecomment-865085014

I had yet to put a screenshot of the 2.0 implementation.  Please note it's not finalized by any means, if you have any feedback, please do share!  Thanks again for the great suggestions!

**Comment by lreading** [comment]
Closing as this is complete in v2
