### ISSUE TITLE
reduce window white space for bigger model display

### ISSUE THREAD

**Issue by injcristianrojas** [OWASP/threat-dragon#216]
When working with bigger models, the model working area is too small, and it also replicates in the generated PDF. It even shows when zooming in. I include an example:

![image](https://user-images.githubusercontent.com/862690/103815942-e382dd00-5042-11eb-98a7-be1f5673a5fc.png)

**Describe the solution you'd like**:
* More space to work, and less blank space.
* (Optional) zoom controls just for the model.

Working on Fedora Linux 33, using RPM version from the repo.

**Comment by jgadsden** [comment]
With version 2.0 of Threat Dragon we see the same problem, screenshot attached. We need the 'Properties' and 'Threats' Panes to be docked with the lower edge of the window, so that the drawing area and 'Entities' panes can expand to fill the gap.

Note that this also happens with the web app version, just zoom out to see the effect.

<img width="1149" alt="threat-dragon-white-space" src="https://user-images.githubusercontent.com/29352392/153439055-2eafa2eb-2462-45cd-8fcb-402f481eacbe.png">

**Comment by jgadsden** [comment]
@taoyiyang1 - the tutorials/documentation for the drawing package is here : https://x6.antv.vision/en/docs/tutorial/about

Is this issue something you could help with?

**Comment by lreading** [comment]
> With version 2.0 of Threat Dragon we see the same problem, screenshot attached. We need the 'Properties' and 'Threats' Panes to be docked with the lower edge of the window, so that the drawing area and 'Entities' panes can expand to fill the gap.
> 
I'm hoping we can do better with the placement of these panes as well! As it is, it's not looking so great on smaller screens. :( 

If memory serves me, the height for the graph is currently hard-coded in pixels.  This could even be as simple as changing it to use view-height as the unit with a min-size property?

**Comment by jgadsden** [comment]
Hello @lreading - absolutely agree, and you are best placed to do this one
My thought here was that @taoyiyang1 could help out with the actual tutorials and documentation for antv? As 陶一阳 does not have the language barrier here

**Comment by lreading** [comment]
It turns out the graph area isn't super responsive by default.  This means we might need to watch for window resizing events (or zoom events, if such a thing exists?) and redraw.  That might have some performance implications... We could debounce the events to help mitigate that a bit.

I'm going to try to think of a better solution for this before committing anything. If anyone has ideas, please do share! :smile:

**Comment by taoyiyang1** [comment]
> 你好@lreading - 绝对同意，你最适合做这个 我的想法是@taoyiyang1可以帮助提供antv 的实际教程和文档？因为陶一阳在这里没有语言障碍
> 
> 我们可以把这个问题分配给你们两个吗？



@jgadsden Of course, @lreading you can consult me ​​if you have difficulty reading a certain part of the document

**Comment by jgadsden** [comment]
The diagram area is now working as required in version 2.0 : https://www.threatdragon.com/
So this can now be closed
