### ISSUE TITLE
Move  STRIDE, CIA and LINDDUN to manage threats

### ISSUE THREAD

**Issue by andrerferreira** [OWASP/threat-dragon#302]
It isn't clear why STRIDE, CIA and LUNDDU are offered on the top left (desktop), having them under “Manage threats” as an option would have made it more intelligible IMHO

**Comment by lreading** [comment]
I think this is a great point. To me, it'd make most sense having it be right on the edit-threat form.  The fields all stay the same, aside from the threat type (based on model selected).

**Comment by lreading** [comment]
@jgadsden - Is this something we'd like to do in v1 as well?  

I'm also open to feedback on the v2 implementation posted above. :)

**Comment by jgadsden** [comment]
well, the idea was that most companies or dev teams tend to stick with one methodology - either CIA, STRIDE or LINDDUN and my guess is that most teams will not mix and match. I guess it just gets too complicated and messy, and hence the whole diagram is one of CIA / STRIDE / LINDDUN

Originally I did not want to recategorise the threats if we change the diagram type, which meant you can end up with a mix and match. So  I think this is more of a diagram attribute rather than an individual threat attribute. Just my thoughts though

**Comment by lreading** [comment]
Is there any particular reason why threats cannot be free-form?  Maybe have Threat Dragon provide the suggested threats from CIA, LINDDUN, STRIDE via dropdown and/or the threat engine, but also allow a user to enter their own threat types?

**Comment by jgadsden** [comment]
Certainly possible - and maybe a really good argument for having the model type as a pull down like you have shown

What I think we need to cater for is most of companies who use just one model type most of the time, so they do not want to be concerned with specifying the model type each time

CIA is an established type that is still in use, but at times inadequate. STRIDE is used for threat models, whereas LINDDUN is used for privacy models. We have stretched Threat Dragon to cover all 3, but (generalising hugely) tend to stick with one model type or another - especially when it comes to privacy models

So short answer is: yes, if the pull down defaults to the diagram model type then go with it, for sure

**Comment by lreading** [comment]
I'm not 100% sold on my screenshot above being the solution.  I'm going to spend a bit more time thinking on it, but I suspect our community may be better served with enhancements in the threat engine, and having the "type" be more of a meta tag based on context. You recent improvements have given me more food for thought and inspiration, so I think I'll wait on closing this one until we can review it again at a later date. :)

**Comment by jgadsden** [comment]
All is good really, this is a free project so whatever is provided is bound to be much appreciated by the community

I am happy to go with what you decide - mainly because I do not _actually_ know how companies use Threat Dragon

Maybe we need a section in the readme asking for thoughts and feedback on proposed features? Maybe I am not sure

**Comment by jgadsden** [comment]
I will take this on if that is OK @lreading , for me it will be a good introduction to the version 2.0 code

**Comment by lreading** [comment]
Sounds great to me! Let me know if you have any questions or if I can help!

**Comment by jgadsden** [comment]
Closing this issue, because version 2.0 handles the model type selection in a different way

We are no longer actively developing for version 1.6.x, and so this can now be closed (unless @andrerferreira you disagree)
