### ISSUE TITLE
Version 2.0: add panning to the diagram

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#333]
**Describe what problem your feature request solves**
It would be really good to be able to pan the the threat model diagrams. Similar to scrolling but no need to drag or bump

**Describe the solution you'd like**
With scrolling we move the visible area of the diagram by dragging an element or by bumping the edge of the visible area with the mouse/cursor, subject of #331 "Version 2.0: add scrolling"
It would be good to be able to click and hold an empty part of the visible canvas and drag/pan it around.

**Additional context**
This is a nice to have, and not a necessary for the release of version 2.0
This is probably already provided by antv/x6, and if we are in luck it requires enabling in config file:
`threat-dragon/td.vue/src/service/x6/graph/graph.js`

**Comment by lreading** [comment]
> It would be good to be able to click and hold an empty part of the visible canvas and drag/pan it around.

This is already _kind of_ implemented... But was added as more of a proof of concept as opposed to a _finalized_ implementation, so we can change whatever we need to.

Holding shift and clicking/dragging will currently pan.  There's a modal with keyboard shortcuts (click the keyboard icon on the graph view).

The reason it's bound to a hotkey is because of the idea of multi-select.  That was a pretty heavily requested feature, and is partially implemented in v2 as well (at least as far as moving or deleting objects from the graph).  If we have the pan work by clicking and dragging on empty space, then we wouldn't be able to drag over an area for multi-select. Multi-select _can also_ be done by holding ctrl/cmd and selecting individual elements.

**Comment by jgadsden** [comment]
Thanks @lreading - I should have read the keyboard shortcuts more closely :)

Indeed I can pan around the canvas, good to see. I tend to have the canvas snapping back to the original view though ... I will try and see what is happening and can raise a bug if it is real (and not just my sloppy mouse control)
