### ISSUE TITLE
v2 - Implement ThreatModelEdit Save

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#340]
**Describe what problem your feature request solves**
The "save" button on the high-level threat model edit view is currently a no-op.

**Describe the solution you'd like**
Implement the "save" functionality
Github Auth - Save to repository (implemented in backend)
Local Session - Do we download a copy?  We will need to figure out the best way to do this with the electron wrapper in the future.

**Additional context**
The graph functionality is still a WIP, this may break existing models.  v2 currently has a toast message to warn users that using this version may break existing models.
- Do we want to save a _copy_ as `<model_name>.v2.0.json` or similar? Or do we do the overwrite as it's always worked?

**Comment by lreading** [comment]
Part of my initial concerns with keeping the same naming conventions have been partially mitigated by implementing the [threat model upgrade screen](https://github.com/OWASP/threat-dragon/pull/348#issuecomment-1006296451]) in #348 

Just to keep the ball moving, I've implemented the "glue" between the front and back-end as it has always worked.

TODO:
- For local sessions, I'll see there's a way to generate/download a JSON file from pure javascript, without a server.
- Electron will need to have its own code to save directly to disk.

**Comment by lreading** [comment]
As it turns out, attempting to download a file in electron opens the "save dialogue" prompt.  This makes things a bit easier.  I like this behavior, as it's intuitive for the user and requires less complexity with handling electron-specific code.  Additionally, this _may_ resolve the default path issues we see with the `.snap` (time will tell).

**Comment by storkinsj** [comment]
Not able to find electron build yet but some thoughts on 1.x since this is 2.0 and the team is dealing local persistence issues:

-Saving icon inside diagram was not easy to understand (download button) but the ability to save changes with one click is important to retain
-File naming of ".json" means we don't have a standard threat-dragon specific file extension. Here are the side effects:
-.json files no doubt already open visual studio code, eclipse, or something similar for the people using threat dragon.. and that's how they want json files to open
-No doable way to double click to open threat model
-No Threat dragon icon that displays on the files.

I did attempt to drag a threat dragon file onto the electron application but it had no visable effect.

IMHO a 2.0 (major version change) does seem like the right place to change behavior like this; however, I don't think any of the existing 1.0 behavior should necessarily change.

**Comment by ShubhamPalriwala** [comment]
My view on this, firstly a great feature ahead!
Secondly, I might think differently here but for now I feel JSON is the best export format.

Parsing a JSON is easy hence opens a lot of gates for us to reuse it and makes it easier for later features too!

**Comment by storkinsj** [comment]
please have a second look at my comment.

no one is recommending we change the format.

I am recommending we change the file extension.

imagine yes Microsoft office’s xml format based documents open eclipse editor instead of word or excel.

It does not mean the document format is not XML by changing the document extension. as I mentioned above I wrote an exporter that absolutely counts on the format being json.

**Comment by jgadsden** [comment]
Yes, understood - at the moment when I am opening files usijg the 1.x desktop version it does filter for all json files in the project. We can of course keep json and have a Threat Dragon specific extension (.td sort of feels natural).

I think this would be much less of a problem to the community than we might think ... nothing stop TD accepting both .json and .td extensions for example

**Comment by jgadsden** [comment]
FWIW .td file extension is used for :

"The TD file type is primarily associated with Train Simulator.  TD files mostly belong to Train Simulator by Microsoft Corporation."

"The .td file extension is used for Teledisk archive files. Teledisk is a shareware disk archiving utility that was released by Sydex and was very popular in the 1990s."

"The td file extension is used for configuration files for the DOS based Borland Turbo Debugger"

All pretty cool, and I even remember using the Borland C/C++ development environment in the mid 90s.

I guess nobody is going to mix us up with Train Simulator files?

**Comment by lreading** [comment]
My preference would be to keep the `.json` extension.  Where we are using a standard format, I feel like we should use the standard extension for it.  This eliminates the need for any domain knowledge to understand what type of data is in it.  

I'm happy to go with whatever the community thinks is best - but if we do go down the route of using the `td` extension, I like Storkinsj suggestion of using the "double" extension of `.json.td` so that it's still clear what type of data lives in the file. :smile:
