### ISSUE TITLE
modify Z-index of Graph Elements

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#343]
**Describe what problem your feature request solves**
Graph elements can overlap, especially with the introduction of the box/machine style trust boundaries.  When the boundary is above the other elements it "contains", the other elements are not intractable.

**Describe the solution you'd like**
- Buttons to bring forward/send back specific elements
- Have boundaries have a lower default z-index

**Comment by jgadsden** [comment]
This has also been reported by one of our customers in #457

**Comment by jgadsden** [comment]
We are OK in general with over-lap of diagram components, because the Actors, Processes and Stores should not be made to overlap on a threat model data-flow diagram.
It is only the trust boundary box that needs to be sent to the background using zIndex = -1, as this boundary box is intended to overlap other components and so will hide them if it is not in the background
