### ISSUE TITLE
1.6.0 Windows Uninstall file name

### ISSUE THREAD

**Issue by romandolinsky** [OWASP/threat-dragon#356]
**Describe the bug**
After installing threat-dragon using silence arg /S /D=" path to install ", Threat-dragon is installed in the correct position, uninstall file name is "Uninstall OWASP-Threat-Dragon.exe" 

**Expected behaviour**
Uninstall file can be "Uninstall-OWASP-Threat-Dragon.exe".  Uninstall file cannot contend white space.

**Environment**
 - Version: 1.6.0 
 - Platform:  Desktop App
 - OS:  Windows

**To Reproduce**
cmd: .\OWASP-Threat-Dragon-Setup-1.6.0.exe /S /D=C:\Test

**Comment by jgadsden** [comment]
Thanks @romandolinsky - we should be able to correct this in the pipeline. It will also be an issue for our new version 2.0

**Comment by jgadsden** [comment]
Hello @romandolinsky - I have had a search through the electron-builder options and there does not seem any way of getting the Uninstall file name into kebab-case; it is always going to have a space in the name
The way to do the uninstall is to use command `'C:\tmp\Uninstall OWASP-Threat-Dragon.exe'` with single quotes, so that the space in the executable name is not a problem

I can add a note in the documentation that says this

**Comment by jgadsden** [comment]
I have added these instructions to the docs page at https://threatdragon.github.io/install-desktop/
