### ISSUE TITLE
Add identifier to threats in json model

### ISSUE THREAD

**Issue by banzo** [OWASP/threat-dragon#51]
Store, Actor and Process entities are identified by a UUID in the json file, which can be used for integration with other security tools or to compare different versions of the threat model. Would it make sense to add a UUID to identify the Threat entities in the json file?

```json
(...)
{
  "type": "tm.Store",
  "id": "7fffa841-aa9e-4a2a-8a3f-03a47d8a80ae",
  "hasOpenThreats": true,
  "threats": [
    {
      "status": "Open",
      "severity": "High",
      "title": "Component identity spoofing",
      "type": "Spoofing",
      "id" : "**SOME_UUID_HERE**",
      "mitigation": "N/A",
      "description": "Artifact repository is compromised, it contains build artifacts that are tampered with"
    }
  ],
    "text": {
      "text": "Artifact Storage"
    }
}
(...)
```

**Comment by jgadsden** [comment]
Hello @banzo - yes, this is a good enhancement to have.

The changes will probably be in the file `src/services/threatengine.js` in the threat dragon core repo: https://github.com/OWASP/threat-dragon-core

Is this something that you could make the changes for?

**Comment by lreading** [comment]
Relates to #187 - and will likely be addressed as part of that.  I will keep this open to ensure it makes it into whatever the threat engine looks like for v2 though. :smile:

**Comment by lreading** [comment]
Someone has suggested having a numeric value associated with threats for a given diagram (as part of the UI).  While this isn't a unique identifier, I think it makes sense to bundle the work together as part of this issue.

For example, the UI may display:
- 1: Unauthorized Access
- 2: Credential Theft

Then those individual threats will also have a unique ID (UUID) associated as well for integration with other systems.

**Comment by jgadsden** [comment]
I think these are linked but also have different uses. Certainly we need a UUID for the threats. We also need an easy way of referring to threats within a model, along the lines of "let us look at threat number 3, how is it different to threat number 42?"
So the threat number has to be associated with the UUID but not the same, and should probably be an incrementing number for each threat model, so that you could get 'threat number3' occurring in multiple (but separate) threat models
It would be good to display this threat  ID (not UUID) in the top right corner of the threat summary in the left hand pane

**Comment by jgadsden** [comment]
UUID can be obtained with:
```
import { v4 as uuidv4 } from 'uuid';
uuidv4(); // ⇨ '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed'
```
