### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by storkinsj** [OWASP/threat-dragon#53]
**Describe what problem your feature request solves**
Please implement an Undo feature. The editing makes it a bit diffucult to remove accidental additions (mousing over and finding the X and clicking it- which fails after a while anyway). Undo would be absolutely excellent and a standard feature of all editors.

**Describe the solution you'd like**
Platform mapped undo command: Command or Control Z based on browser/electron info

**Additional context**

**Comment by jgadsden** [comment]
Hello @storkinsj 

Agreed, this is missing from the Threat Dragon diagram package. All to do with using the free-to-use version of JointJS - the paid for version has this as standard. This issue is similar to: 
https://github.com/OWASP/threat-dragon-core/issues/4

When we migrate to mxgraph (the drawing package behind draw.io) then we should get undo/redo .

Thanks again for the good issues being raised

**Comment by lreading** [comment]
Closing as this is complete in v2
