### ISSUE TITLE
Incomplete STRIDE in Added Threat

### ISSUE THREAD

**Issue by IdanAmitay** [OWASP/threat-dragon#614]
**Describe the bug**

When creating new threat on STRIDE model only the "Spoofing" and "Repudiation" appear as options.

**Expected behaviour**

Full STRIDE options to appear

**Environment**
 - Version: 2.0.1
 - Platform: Desktop App
 - OS: MacOS
 - Browser: Chrome

**To Reproduce**

Mark any "Actor" rectangle and add threat

**Any additional context, screenshots, etc**

![2023-03-02_15-28-24](https://user-images.githubusercontent.com/84445532/222444707-bb96e0db-3b95-410b-a535-45dabbba78b4.png)

**Comment by jgadsden** [comment]
Hello @IdanAmitay 

This is the behaviour by design - we implement STRIDE by element and this is documented at https://www.threatdragon.com/docs/usage/modeling/threats.html

### Threats by element
Some threat categories are associated with some diagram elements more than others.
For example an Actor element is more likely to have Spoofing and Repudiation threats
associated with it, and less likely to be vulnerable to
Tampering, Information disclosure, Denial of service or Elevation of privileges.

According to the type of diagram (STRIDE, LINDDUN and CIA),
Threat Dragon will restrict the threat type according to the element.

**Comment by jgadsden** [comment]
If you would like the full range of threat types for a element type then you can change the diagram type to 'Generic' - this gives you everything
Hope that helps @IdanAmitay and I can close this issue now

**Comment by IdanAmitay** [comment]
Thanks for the rapid response @jgadsden
