### ISSUE TITLE
Clicking on data flow does not open it in properties

### ISSUE THREAD

**Issue by jbaptistemariebio** [OWASP/threat-dragon#785]
**Describe the bug**:
Clicking on an existing data flow does not set its properties into the properties section. A double click is needed, but it results in an addition of a new point on the data flow.

**Expected behaviour**:
A single click on the data flow makes its properties accessible in the properties section

**Environment**:

- Version: 2.1.1
- Platform: Desktop App and Web App
- OS: MAC OS / Windows / Linux
- Browser: All

**To Reproduce**:
1. Add a data flow
2. Select another component on the diagram
3. Click on the data flow just created

**Comment by jgadsden** [comment]
I understand the frustration @jbaptistemariebio , but this is the behaviour inherited from the drawing package and can not be changed. If you need to select with a single click then use the end points of the dataflow and click on either of them

**Comment by jgadsden** [comment]
We can try and improve the documentation to emphasise this behaviour, given that there is not much we can do about it

**Comment by hilari0n** [comment]
I'm on Windows, on Threat Dragon (desktop app) 2.1.3.0 and have the same issue.
The workaround to click on the end point does not work for all data flows. I.e. if an end of the data flow is attached to a process, then clicking at the end of the data flow attached to it is not possible - the process gets selected. So if both ends of a data flow are attached to a process, you can't access properties by a simple single-click.
Is there an alternative to "select with a single click"? I.e., I don't need this to be a single click, I just need a working way to access the properties and threats of a data flow. (I tried the "Tab" key, right-click, double-click.)

And just before posting this I accidentally stumbled upon a workaround to the workaround. I.e., if your data flow ends are tied to a process, and you can't simply click the end of the data flow, because it selects the process, the solution may be (works for me, at least for the couple of cases I tested) to first hover the mouse cursor over the data flow, for it's boundary box to appear, and then carefully move the cursor along the data flow until its end (making sure not to leave the boundary box), i.e., until the cursor changes (to show, that you can grab and move the ending point) and then click it. It may not be trivial, if the data flow line area between the processes is small. You can use zoom in, to make it a bit easier.

**Comment by MaSven** [comment]
Would it help to have a list of the objects on the side? At least this would make it possible the edit them from there.

**Comment by jgadsden** [comment]
will have another attempt at improving the selectability of the dataflows and trust boundaries

**Comment by jgadsden** [comment]
This is fixed in pull request 'Migrate to version 2.x antv/x6' https://github.com/OWASP/threat-dragon/pull/1099, where the selection of dataflows and trust boundary curves is greatly improved
