### ISSUE TITLE
Menu "Open Recent" doesn't show recent models

### ISSUE THREAD

**Issue by genseirin** [OWASP/threat-dragon#990]
**Describe the bug**:

Menu "Open Recent" remains empty although I opened a model before. There is only an entry "Clear Menu".

**Expected behaviour**:

There should be an entry of the model that I opened last time.

**Environment**:

- Version: 2.2.0.0 and above
- Platform: Desktop App
- OS: Windows and Linux
- Browser: N/A

**To Reproduce**:

1. Open a model
2. Optionally save it
3. Close it, or close and reopen the application
4. Check the menu File -> Open Recent

**Any additional context, screenshots, etc**:

![image](https://github.com/OWASP/threat-dragon/assets/1910838/c17a93c6-2412-4bdb-9e6c-aa1c38b11f18)

**Comment by jgadsden** [comment]
This has probably only been tested on Linux and MacOS

**Comment by Suvendu-UI** [comment]
for reproducing this issue, do we have to join the threat dragon ?

**Comment by jgadsden** [comment]
@Suvendu-UI this is the desktop version running on Windows only - as far as I can tell

**Comment by jgadsden** [comment]
This issue is also for Linux as well as Windows, so the only platform it works for is MacOS

**Comment by jgadsden** [comment]
From the [electron documentation](https://www.electronjs.org/docs/latest/tutorial/recent-documents#windows-notes) Windows notes : 
_To use this feature on Windows, your application has to be registered as a handler of the file type of the document, otherwise the file won't appear in JumpList even after you have added it. You can find everything on registering your application in [Application Registration](https://learn.microsoft.com/en-us/windows/win32/shell/app-registration)._
